config/routes.rb
Rails.application.routes.draw do
  # get 'ingredients/new'
  # get 'ingredients/create'
  # get 'ingredients/edit'
  # get 'ingredients/update'
  # get 'ingredients/destroy'
  # get 'sessions/new'
  # get 'users/new'
  get root 'recipes#index'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/easy_login',   to: 'sessions#easy_login'
  delete '/logout',  to: 'sessions#destroy'
  get '/recipes', to: 'recipes#index'
  resources :users do
    member do
      get :liking
    end
  end
  # resources :account_activations, only: [:edit]
  # resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :recipes do
    member do
      get :likers
    end
  end
  resources :categories do
    member do
      get :recipe
    end
  end
  resources :instructions, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :instructions, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :instructions, allow_destroy: true
  accepts_nested_attributes_for :ingredients, allow_destroy: true
  has_many :passive_likes, class_name: "Like",
                 foreign_key: "liked_id",
                 dependent: :destroy
  has_many :likers,
                   through: "passive_likes",
                   source: "liker"
  has_many :recipe_category_relations, dependent: :destroy
  has_many :categories, through: "recipe_category_relations"
  # default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size:         { less_than: 5.megabytes,
                                    message: "should be less than 5MB" }

  def display_image(width, height)
    image.variant(resize_to_limit: [width, height])
  end

  # def display_image_200
  #   image.variant(resize_to_limit: [200, 200])
  # end
  #
  # def display_image_400
  #   image.variant(resize_to_limit: [400, 400])
  # end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    if params[:option] == "recent" || params[:option] == nil
      @page_title = "Latest Recipes"
      @recipes = Recipe.all.order(created_at: :desc).paginate(page: params[:page], per_page: 36)
    elsif params[:option] == "popular"
      @page_title = "Popular Recipes"
      # recipes_hash = Recipe.joins(:passive_likes).group("liked_id").order('count_all DESC', created_at: :desc).count
      recipes_hash = Recipe.joins(:passive_likes).group("liked_id").order('count_all DESC').count
      recipe_ids = recipes_hash.keys
      recipe_array = Recipe.find(recipe_ids).sort_by{ |recipe| recipe_ids.index(recipe.id)}
      @recipes = Kaminari.paginate_array(recipe_array).page(params[:page]).per(20)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    # @recipe = current_user.recipes.build if logged_in?
    @recipe = Recipe.new
    4.times { @recipe.ingredients.build }
    3.times { @recipe.instructions.build }

  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    @recipe.image.attach(params[:recipe][:image])
    if @recipe.save
      flash[:success] = "Recipe created! / レシピが投稿されました。"
      redirect_to recipes_url
    else
      render 'recipes/new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe updated / 更新に成功しました。"
      redirect_to @recipe
      #更新に成功した場合に扱う
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted / レシピを削除しました。"
    redirect_to root_url
  end

  private

  # def recipe_params
  #   params.require(:recipe).permit(:content, :image)
  # end

  def recipe_params
    params.require(:recipe).permit(:title, :about, :image, :_destroy,
                              category_ids: [],
                              instructions_attributes: [:id, :no, :how_to, :_destroy],
                              ingredients_attributes: [:id, :ingre, :amount, :_destroy]
                            )
  end

  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    redirect_to root_url if @recipe.nil?
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_category.html.erb
<% unless @recipe.category_ids.empty? %>
      <div class="d-inline-block mr-2">
        <p class="category_title">Category</p>
      </div>
      <div class="d-inline-block">
        <span>
          <% @recipe.categories.each do |category| %>
          <%= link_to category.name, recipe_category_path(id: category.id), class: "category-button" %>
          <% end %>
        </span>
      </div>
  <% end %>

app/views/recipes/_recipe.html.erb
<ol id="recipe-<%= recipe.id %>" class="item">
  <div class="recipe">
    <div class="recipe_item">
        <p class="recipe_title"><%= link_to  recipe.title , recipe_path(recipe) %></p>
        <p class="recipe_about"><%= recipe.about.truncate(213)  %></p>
        <% if recipe.image.attached? %>
          <%= link_to recipe_path(recipe) do %>
            <%= image_tag(recipe.display_image(250,200), class: "recipe_img")%>
          <% end %>
        <% else %>
        <!--<img src="/assets/no-image.jpg" alt="no-image" width="250" height="200" class="rounded">-->
         <%= image_tag 'no-image.jpg', :size => '250x200',:class=> 'recipe_img', :alt => 'no-image'  %>
        <% end %>
        <!-- <%= link_to image_tag("favicon.png", alt: "logo", width: "40px"),root_path, class: "logo"  if recipe.image.attached? %> -->
        <p class="recipe_timestamp">Posted <%= time_ago_in_words(recipe.created_at) %> ago.</p>
        <p class="user"><%= link_to recipe.user.name, recipe.user %></p>

          <div class="like_div">
            <div class="like_display">
              <%= render partial: 'shared/like_form', locals: {recipe: recipe}%>
              <div id="likers<%=recipe.id%>" class="d-inline-block likers_count" >
                <%= render partial: 'shared/likers_count', locals: {recipe: recipe}%>
              </div>
            </div>
          </div>

          <div class="recipe_fix">
            <% if current_user?(recipe.user) %>
                <p class="delete"><%= link_to "Delete", recipe, method: :delete,
                                              data: { confirm: "You sure?" } %></p>
                <p><%= link_to "Edit", edit_recipe_path(recipe) %></p>
              <% else %>
                <p style="margin-bottom: 13px;"></p>
            <% end %>
          </div>
    </div>
  </div>
</ol>

app/views/recipes/_supplement.html.erb
<div class="row supplement">
  <div class="col-sm-8 float-left">
    <%= render 'category'%>
  </div>
  <div class="col-sm-4 recipe_show_like_div">
    <% if current_user?(recipe.user) %>
      <div class="edit_delete">
          <p class="delete_show"><%= link_to "Delete", recipe, method: :delete,
                                              data: { confirm: "You sure?" } %></p>
          <p class="edit_show"><%= link_to edit_recipe_path(recipe), class:"" do%>
            Edit
          <% end %></p>
      </div>
    <% end %>
    <div class="like_display">
      <%= render partial: 'shared/like_form', locals: {recipe: recipe}%>
      <div id="likers<%=recipe.id%>" class="d-inline-block likers_count" >
        <%= render partial: 'shared/likers_count', locals: {recipe: recipe}%>
      </div>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<% provide(:title, "Edit recipe") %>
<% provide(:button_text, 'Update / 更新する') %>
<h1>Update recipe</h1>
<section class="recipe_form">
  <%= render 'shared/recipe_form' %>
</section>

app/views/recipes/index.html.erb
<% provide(:title, "Recipes") %>

<div class="recipe-index__content">
  <h2 class="recipe-index__title"><%= @page_title %></h2>
     <% if @category.nil? %>
      <p class="d-inline-block"><%= link_to "Latest",   recipes_path(option: "recent") %> | <%= link_to "Popular",   recipes_path(option: "popular")%></p>
    <% else%>
      <p class="d-inline-block"><%= link_to "Latest(#{@category.name})",   recipe_category_path(id: @category.id, option: "recent") %></p>
      <p class="d-inline-block">     |     </p>
      <p class="d-inline-block"><%= link_to "Popular(#{@category.name})",   recipe_category_path(id: @category.id, option: "popular") %></p>
    <% end %>
    <div class="grid">
        <%= render @recipes %>
    </div>
    <%= will_paginate @recipes %>
</div>

app/views/recipes/new.html.erb
<% provide(:title, "Post Recipe") %>
<% provide(:button_text, 'Post/投稿する') %>
<div class="recipe_form">
  <%= render 'shared/recipe_form' %>
</div>

app/views/recipes/show.html.erb
<% recipe ||= @recipe%>
<% provide(:title, @recipe.title)%>
<div class="recipe-show">
  <h1 class="recipe-show__title">
  <%= @recipe.title %>
  </h1>
  <%= render partial: 'supplement', locals: {recipe: @recipe}%>


   <div class="row">
    <div class="col-md-5">
      <section class="information mt-2">
        <%# <p class="about">About</p> %>
        <% if @recipe.image.attached? %>
          <%= image_tag @recipe.display_image(540, 400), class: "img-fluid rounded recipe-show__img" %>
        <% end %>
        <%#<p class="recipe-about mt-2"><%= @recipe.about %><%#</p>%>
      </section>
    </div>
    <div class="col-md-5 offset-md-2">
      <section class="information">
        <p class="recipe-show__about mt-2"><%= @recipe.about %></p>
        <div class="recipe-show__posted-by mr-4">
          <p class="d-inline-block mr-1">Posted by</p>
         <p class="d-inline-block"><%= link_to @recipe.user.name, @recipe.user %></p>
        </div>
        <h2 class="ingre__title">Ingredients / 材料</h2>
        <% ingredients = @recipe.ingredients.all %>
        <% ingredients.each do |ingre| %>
          <ol class="ingre__ol">
            <p class="ingre__item"><%= ingre.ingre %></p>
            <p class="ingre__amount"><%= ingre.amount %></p>
            <br>
          </ol>
        <% end %>
      </section>
    </div>
  </div>
  <div class="row instruction">
    <div class="col-md-12">
    <h2 class="instruction__title">Instruction / 作り方</h2>
    <% instructions = @recipe.instructions.all %>
    <% i = 1%>
    <% instructions.each do |inst| %>
      <ol class="instructions">
        <!-- <p><%= inst.no %></p> -->
        <p class="d-inline-block mr-2"><%= i %>.</p>
        <!--<p class="d-inline-block"><%= inst.how_to %></p>-->
        <p class="d-inline-block"><%= safe_join(inst.how_to.split("\n"), tag(:br)) %></p>
        <br>
        <% i += 1%>
      </ol>
    <% end %>
  </div>
</div>
</div>