config/routes.rb
Rails.application.routes.draw do
  # get 'ingredients/new'
  # get 'ingredients/create'
  # get 'ingredients/edit'
  # get 'ingredients/update'
  # get 'ingredients/destroy'
  # get 'sessions/new'
  # get 'users/new'
  get root 'recipes#index'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/easy_login',   to: 'sessions#easy_login'
  delete '/logout',  to: 'sessions#destroy'
  get '/recipes', to: 'recipes#index'
  resources :users do
    member do
      get :liking
    end
  end
  # resources :account_activations, only: [:edit]
  # resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :recipes do
    member do
      get :likers
    end
  end
  resources :categories do
    member do
      get :recipe
    end
  end
  resources :instructions, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  has_many :active_likes, class_name: "Like", foreign_key: "liker_id",
                  dependent: :destroy
  has_many :liking,
                  through: 'active_likes',
                  source: 'liked'
  attr_accessor :remember_token
  before_save {email.downcase!}
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
   update_attribute(:remember_digest, nil)
  end

  def like(recipe)
    liking << recipe
  end

  def unlike(recipe)
    self.active_likes.find_by(liked_id: recipe.id).destroy
  end

  def liking?(recipe)
    self.liking.include?(recipe)
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy


  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    if params[:option] == "recent" || params[:option] == nil
      @recipes = @user.recipes.order(created_at: :desc).paginate(page: params[:page])
    elsif
      recipes_hash = @user.recipes.joins(:passive_likes).group("liked_id").order('count_all DESC').count
      recipe_ids = recipes_hash.keys
      recipe_array = Recipe.find(recipe_ids).sort_by{ |recipe| recipe_ids.index(recipe.id)}
      @recipes = Kaminari.paginate_array(recipe_array).page(params[:page]).per(20)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Recipes from Japan!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated / 更新に成功しました。"
      redirect_to @user
      #更新に成功した場合に扱う
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted / ユーザーを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                      :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<ul>
  <%= link_to user.name, user %>
  <% if current_user%>
    <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "You sure?" } %>
    <% end %>
  <% end %>
<ul>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes / 更新する') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3 user-edit">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
  <ul class="users">
      <%= render @users %>
  </ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Sign up / 登録する') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 sign-up-form">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="recipe-index__content">
  <h2 class="recipe-index__title">
    <%= @user.name %>
      <% if @user.recipes.any? %>
        's Recipes (<%= @user.recipes.count %>)
      <% end %>
  </h2>
     <% if @category.nil? %>
      <p class="d-inline-block"><%= link_to "Recent",   user_path(@user, option: "recent") %> |
      <%= link_to "Popular",  user_path(@user, option: "popular") %></p>
    <% else%>
      <p class="d-inline-block"><%= link_to "Latest(#{@category.name})",   recipe_category_path(id: @category.id, option: "recent") %></p>
      <p class="d-inline-block">     |     </p>
      <p class="d-inline-block"><%= link_to "Popular(#{@category.name})",   recipe_category_path(id: @category.id, option: "popular") %></p>
    <% end %>
    <div class="grid">
        <%= render @recipes %>
    </div>
    <%= will_paginate @recipes %>
</div>