config/routes.rb
Rails.application.routes.draw do
  # get 'ingredients/new'
  # get 'ingredients/create'
  # get 'ingredients/edit'
  # get 'ingredients/update'
  # get 'ingredients/destroy'
  # get 'sessions/new'
  # get 'users/new'
  get root 'recipes#index'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/easy_login',   to: 'sessions#easy_login'
  delete '/logout',  to: 'sessions#destroy'
  get '/recipes', to: 'recipes#index'
  resources :users do
    member do
      get :liking
    end
  end
  # resources :account_activations, only: [:edit]
  # resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :recipes do
    member do
      get :likers
    end
  end
  resources :categories do
    member do
      get :recipe
    end
  end
  resources :instructions, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :instructions, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :instructions, allow_destroy: true
  accepts_nested_attributes_for :ingredients, allow_destroy: true
  has_many :passive_likes, class_name: "Like",
                 foreign_key: "liked_id",
                 dependent: :destroy
  has_many :likers,
                   through: "passive_likes",
                   source: "liker"
  has_many :recipe_category_relations, dependent: :destroy
  has_many :categories, through: "recipe_category_relations"
  # default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size:         { less_than: 5.megabytes,
                                    message: "should be less than 5MB" }

  def display_image(width, height)
    image.variant(resize_to_limit: [width, height])
  end

  # def display_image_200
  #   image.variant(resize_to_limit: [200, 200])
  # end
  #
  # def display_image_400
  #   image.variant(resize_to_limit: [400, 400])
  # end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_ingredient_fields.html.erb
<div class="nested-fields form-row">
  <%= f.hidden_field :_destroy %>
  <div class="form-group col-7">
    <% f.label :ingre, "Ingredient / \n原材料" %>
    <%= f.text_field :ingre, class: 'form-control'%>
  </div>
  <div  class="form-group col-4">
    <% f.label :amount, "Amount / \n分量" %>
    <%= f.text_field :amount, class: 'form-control' %>
  </div>
  <div class="form-group col-1 remove">
    <%= link_to "×", "#", class: "remove_fields" %>
  </div>
</div>

app/views/shared/_instruction_fields.html.erb
<div class="nested-fields form-row">
  <%= f.hidden_field :_destroy %>
  <div class="form-group col-2 col-md-1">
    <% f.label :no, "No." %>
    <%= f.telephone_field :no, class: 'form-control' , value: "#{@order_number}" %>
    <% @order_number += 1 %>
  </div>
  <div class="form-group col-9 col-md-10 ">
      <% f.label :how_to, "instruction / 作り方" %>
      <%= f.text_field :how_to, class: 'form-control' %>
  </div>
  <div class="form-group col-1 remove">
    <%= link_to "×", "#", class: "remove_fields"%>
  </div>

</div>

app/views/shared/_like.html.erb
<div class="d-inline-block">
  <%= form_for(current_user.active_likes.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :liked_id, recipe.id%></div>
    <%= f.button type: "submit" do%>
      <i class="far fa-heart like-btn" ></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_like_form.html.erb
  <div  id = "like_form<%=recipe.id%>"  class="d-inline-block like_form">
      <% if logged_in?%>
          <%if current_user.liking?(recipe) %>
              <%= render partial: "shared/unlike", locals: {recipe: recipe}%>
            <%else%>
              <%= render partial: "shared/like", locals: {recipe: recipe}%>
          <%end%>
      <% else %>
          <i class="far fa-heart like-btn d-inline-block" ></i>
      <% end%>
  </div>

app/views/shared/_likers_count.html.erb
<div class="d-inline-block likers_count" >
  <% if recipe.likers.count > 0%>
    <%= recipe.likers.count %>
  <% else %>
    <div class="mr-2"> </div>
  <%end%>
</div>

app/views/shared/_recipe_form.html.erb
    <h1 class="recipe_title_show">Post Recipe / レシピの投稿</h1>
    <%= form_with model: @recipe,local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    <div class="row recipe_form__field">
      <div class="col-lg-5">
       <fieldset>
        <legend></legend>
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>

          <%= f.label :about, "About Recipe / コメント" %>
          <%= f.text_area  :about, class: 'form-control' %>

        <span class="image">
          <%= f.label :image, "Recipe Image / 料理画像" %>
          <%= f.file_field :image %>
        </span>

        <legend>Categories</legend>
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name,  include_hidden: false ) do |category| %>
            <%= category.label class:"recipe_form__ctgry_checkbox" do %>
              <%= category.text %>
              <%= category.check_box %>
            <%end%>
          <% end %>
      </fieldset>
      </div>

      <div class="col-lg-5 offset-lg-2">
        <fieldset>
          <legend class="row">
            <%# <div class="row"> %>
              <div class="post-ingre col-7">ingredient/原材料</div>
              <div class="post-ingre col-5">amount/分量</div>
            <%# </div> %>
          </legend>
          <%= f.fields_for :ingredients do |ingredients_form| %>
            <%= render "shared/ingredient_fields", f: ingredients_form %>
          <% end %>
          <div class="add_ingre_btn">
            <%= link_to_add_fields "Add Ingredients / 原材料の追加", f, :ingredients %>
          </div>
        </fieldset>
        </div>

        <div class="col-12">
        <fieldset>
          <legend>
          <div class="row">
            <div class="col-1">No.</div>
            <div class="col-10">instruction / 作り方</div>
          </div>
          </legend>
          <% @order_number = 1 %>
            <%= f.fields_for :instructions do |instructions_form|%>
              <%= render "shared/instruction_fields", f: instructions_form %>
            <% end %>
            <div class="add_inst_btn">
              <%= link_to_add_fields "Add Instruction / 工程追加", f, :instructions %>
            </div>
        </fieldset>
              <%= f.submit yield(:button_text), class: "btn btn-dark col-4 offset-4 col-lg-2 col-lg-offset-5" %>
          <% end %>
        </div>
    </div>

        <script type="text/javascript">
          $("#recipe_image").bind("change", function() {
            var size_in_megabytes = this.files[0].size/1024/1024;
            if (size_in_megabytes > 5) {
              alert("Maximum file size is 5MB. Please choose a smaller file.");
              $("#recipe_image").val("");
            }
          });
        </script>

app/views/shared/_unlike.html.erb
<div class="d-inline-block">
  <%= form_for(current_user.active_likes.find_by(liked_id: recipe.id),
          html: {method: :delete}, remote: true) do |f| %>
    <%= f.button type: "submit" do%>
      <i class="fas fa-heart unlike-btn" ></i>
    <% end %>
  <% end %>
</div>