config/routes.rb
Rails.application.routes.draw do
  # get 'ingredients/new'
  # get 'ingredients/create'
  # get 'ingredients/edit'
  # get 'ingredients/update'
  # get 'ingredients/destroy'
  # get 'sessions/new'
  # get 'users/new'
  get root 'recipes#index'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/easy_login',   to: 'sessions#easy_login'
  delete '/logout',  to: 'sessions#destroy'
  get '/recipes', to: 'recipes#index'
  resources :users do
    member do
      get :liking
    end
  end
  # resources :account_activations, only: [:edit]
  # resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :recipes do
    member do
      get :likers
    end
  end
  resources :categories do
    member do
      get :recipe
    end
  end
  resources :instructions, only: [:new, :create, :edit, :update, :destroy]
  resources :ingredients, only: [:new, :create, :edit, :update, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_concept.html.erb
<div class="concept">
  <%= image_tag('concept.jpg', :class => "concept__img")%>
  <p class="concept__text">
    <a class="concept__msg">Please enjoy Japanese home-made dishes at your dining!</a>
  </p>
</div>

app/views/layouts/_footer.html.erb
<footer  class="navbar navbar-default navbar-fixed-bottom">
    <div class="footer__copyright"><span>&copy;</span> Recipes from Japan All Rights Reserverd</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse ">
      <div class="header title">
          <%= link_to image_tag("favicon.png", alt: "logo", width: "40px"),
                          root_path, {class: "logo"} %>
          <%= link_to "Recipes from Japan", root_path, {class: "logo"} %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Recipes",   recipes_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Category <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
              <% Category.all.each do |category| %> 
                <li><%= link_to category.name, recipe_category_path(id: category.id) %></li>
              <% end %>
              </ul>
            </li>
            <% if logged_in? %>
               <li><%= link_to "Post recipe", new_recipe_path %></li>
               <li><%= link_to "Users", users_path %></li>
               <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                   Account <b class="caret"></b>
                 </a>
                 <ul class="dropdown-menu">
                   <li><%= link_to "Profile", current_user %></li>
                   <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                   <li class="divider"></li>
                   <li>
                     <%= link_to "Log out", logout_path, method: :delete %>
                   </li>
                 </ul>
               </li>
       <% else %>
         <li><%= link_to "Users", users_path %></li>
         <li><%= link_to "Sign up",  signup_path %></li>
         <li><%= link_to "Log in", login_path %></li>
       <% end %>
         <!-- <li><%= link_to "About",   about_path %></li>
         <li><%= link_to "Contact",   contact_path %></li> -->
     </ul>
   </nav>
 </div>
</header>

app/views/layouts/_header2.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light navbar-fixed-top bg-light " style="background-color: #e3f2fd;">
    <%= link_to root_path, class: "logo item" do%>
      <%= image_tag("favicon.png", alt: "logo", width: "40px")%>
      Recipes from Japan
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse item" id="navbarSupportedContent">
    <ul class="navbar-nav mr-0">
        <li class="nav-item">
          <%= link_to recipes_path, {class: "nav-link"} do %>
          <%# <span class="glyphicon glyphicon-cutlery" aria-hidden="true">Recipes</span> %>
          <i class="fas fa-utensils">Recipe</i>
          <% end %>
        </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%# <span class="glyphicon glyphicon-list" aria-hidden="true">Category</span> %>
          <%# <span class="glyphicon glyphicon-folder-open" aria-hidden="true">Category</span> %>
          <%# <span class="glyphicon glyphicon-th" aria-hidden="true">Category</span> %>
          <i class="fas fa-th">Category</i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <% Category.all.each do |category| %>
                <%# <a class="dropdown-item nav-link", display> %>
                <%= link_to recipe_category_path(id: category.id), {class: "dropdown-item nav-link nav-link"} do %>
                  <span><%= category.name%></span>
                <% end %>
                <%# </a> %>
           <% end %>
        </div>
      </li>
      <% if logged_in? %>
      <li class="nav-item">
      <%= link_to new_recipe_path, {class: "nav-link"} do%>
      <%# <span class="glyphicon glyphicon-share" aria-hidden="true">Post&thinsp;recipe</span> %>
      <i class="fas fa-edit">Post&thinsp;recipe</i>
      <% end %>
      </li>
      <li class="nav-item">
      <%= link_to  users_path, {class: "nav-link"} do %>
        <i class="fas fa-users">Users</i>
      <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user">Account</i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to current_user, {class: "nav-link dropdown-item"} do %>
              <i class="fas fa-address-card">Profile</i>
            <% end %>
            <%= link_to edit_user_path(current_user), {class: "nav-link dropdown-item"} do %>
              <i class="fas fa-user-cog">Setings</i>
            <% end %>
           <div class="dropdown-divider"></div>
            <%= link_to logout_path, {method: :delete, class: "nav-link dropdown-item"} do %>
              <i class="fas fa-sign-out-alt">Log&thinsp;out</i>
            <% end %>
         </div>
      </li>
      <% else %>
      <li class="nav-item">
      <%= link_to  users_path, {class: "nav-link"} do %>
        <i class="fas fa-users">Users</i>
      <% end %>
      </li>
      <li class="nav-item">
      <%= link_to signup_path, {class: "nav-link"} do %>
        <i class="fas fa-user-plus">Sign up</i>
        <% end %>
      </li>
       <li class="nav-item">
       <%= link_to login_path, {class: "nav-link"} do %>
       <i class="fas fa-sign-in-alt">Log in</i>
       <% end %>
       </li>
      <% end %>
    </ul>
  </div>
  </nav>
</header>

app/views/layouts/_message.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
   <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="Recipe site of Japanese home cokking">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous"> %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    <!--<link href="https://fonts.googleapis.com/css2?family=Philosopher&display=swap" rel="stylesheet">-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700&family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.png') %>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header2' %>
    <div class="body">
      <%= render 'layouts/concept' %>
      <div class="container">
        <%= render 'layouts/message' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>